version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:8.0  # Utilisation de l'image Docker OpenJDK 8

    steps:
      - checkout  # Récupération du code source

      # Compilation sans exécuter les tests
      - run:
          name: Build (without tests)
          command: mvn -B -DskipTests clean package

      # Compilation complète avec Maven
      - run:
          name: Build with Maven
          command: mvn clean install

      # Exécution des tests et génération du rapport de couverture
      - run:
          name: Run Tests and Generate Coverage Report
          command: mvn test jacoco:report

      # Envoi du rapport de couverture à Codecov
      - run:
          name: Upload Coverage to Codecov
          command: bash <(curl -s https://codecov.io/bash)

      # Exécution de l'analyse Checkstyle
      - run:
          name: Checkstyle Analysis
          command: mvn checkstyle:check

# Orchestration des jobs dans le workflow
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
