# Utilisation de la version 2.1 de l'engine de pipeline de CircleCI
# Voir : https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

# Définition des jobs pour le workflow
jobs:
  build:
    docker:
      - image: cimg/openjdk:8.0

    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Build with Maven
          command: mvn clean install
      - run:
          name: Run Tests and Generate Coverage Report
          command: mvn test jacoco:report

  upload_codecov:
    docker:
      - image: cimg/openjdk:8.0
    steps:
      - checkout
      - run:
          name: Upload Coverage to Codecov
          command: codecov/upload  # orbe Codecov sans token pour dépôt public

# Orchestration des jobs dans le workflow
workflows:
  version: 2
  build_and_upload:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
      - upload_codecov:
          requires:
            - build
          filters:
            branches:
              only:
                - master
