# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/jobs-steps/#jobs-overview & https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build:
    docker:
      - image: cimg/openjdk:8.0

    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Build with Maven
          command: mvn clean install
      - run:
          name: Generate Coverage Report
          command: mvn test jacoco:report

  upload_codecov:
    docker:
      - image: cimg/openjdk:8.0
    steps:
      - checkout
      - codecov/upload

# Orchestrate jobs using workflows
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
      - upload_codecov:
          requires:
            - build
          filters:
            branches:
              only:
                - master
