version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:8.0

    steps:
      - checkout

      # Compilation sans exécuter les tests
      - run:
          name: Build (without tests)
          command: mvn -B -DskipTests clean package

      # Compilation complète avec Maven
      - run:
          name: Build with Maven
          command: mvn clean install

      # Exécution des tests et génération du rapport de couverture
      - run:
          name: Run Tests and Generate Coverage Report
          command: mvn test jacoco:report

      # Envoi du rapport de couverture à Codecov
      - run:
          name: Upload Coverage to Codecov
          command: bash <(curl -s https://codecov.io/bash)

      # Exécution de l'analyse Checkstyle
      - run:
          name: Checkstyle Analysis
          command: mvn checkstyle:check

      # Compilation du projet et génération de la Javadoc
      - run:
          name: Build and Generate Javadoc
          command: mvn clean javadoc:javadoc

      # Publier la Javadoc sur GitHub Pages
      - run:
          name: Deploy Javadoc to GitHub Pages
          command: |
            mkdir -p target/github-pages
            cp -r target/site/apidocs/* target/github-pages/
            git config --global user.email "oumayma.bousaid@gmail.com"
            git config --global user.name "Oumayma-Bousaid"
            git clone git@github.com:${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}.git gh-pages
            cd gh-pages
            git checkout -b gh-pages || git checkout gh-pages
            cp -r ../target/github-pages/* .
            git add .
            git commit -m "Update Javadoc"
            git push origin gh-pages --force


# Orchestration des jobs dans le workflow
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
