version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:8.0

    steps:
      # Étape 1 : Cloner le code source
      - checkout

      # Étape 2 : Compilation du projet
      - run:
          name: Build with Maven
          command: mvn clean install -DskipTests

      # Étape 3 : Exécution des tests et génération de la couverture de code
      - run:
          name: Run Tests and Generate Coverage Report
          command: mvn test jacoco:report

      # Étape 4 : Envoi des données de couverture à Codecov
      - run:
          name: Upload Coverage to Codecov
          command: |
            if [ -n "$CODECOV_TOKEN" ]; then
              bash <(curl -s https://codecov.io/bash)
            else
              echo "Codecov token is not set. Skipping upload."
            fi

      # Étape 5 : Analyse Checkstyle pour respecter les normes de codage
      - run:
          name: Checkstyle Analysis
          command: mvn checkstyle:check

      # Étape 6 : Configuration SSH pour le déploiement GitHub Pages
      - add_ssh_keys:
          fingerprints:
            - "SHA256:/Bq0fKHvAXKoEqKoFMUqXnrsYDGj9SEXrhmQv1htK3M"
      - run:
          name: Configure SSH and Git
          command: |
            eval "$(ssh-agent -s)"
            ssh-add ~/.ssh/id_rsa
            git remote set-url origin git@github.com:${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}.git

      # Étape 7 : Génération de la documentation Javadoc
      - run:
          name: Generate Javadoc
          command: mvn javadoc:javadoc

      # Étape 8 : Déploiement de la Javadoc sur GitHub Pages
      - run:
          name: Deploy Javadoc to GitHub Pages
          command: |
            mkdir -p target/github-pages
            cp -r target/site/apidocs/* target/github-pages/
            git config --global user.email "oumayma.bousaid@gmail.com"
            git config --global user.name "Oumayma-Bousaid"
            git clone git@github.com:${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}.git gh-pages
            cd gh-pages
            git checkout gh-pages || git checkout -b gh-pages
            cp -r ../target/github-pages/* ./
            git add .
            git commit -m "[skip ci] Updated Javadoc"
            git push origin gh-pages --force

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
