jobs:
  build:
    docker:
      - image: cimg/openjdk:8.0

    steps:
      - checkout

      # Compilation avec Maven
      - run:
          name: Build with Maven
          command: mvn clean install -DskipTests

      # Exécution des tests et génération du rapport de couverture
      - run:
          name: Run Tests and Generate Coverage Report
          command: mvn test jacoco:report

      # Envoi du rapport de couverture à Codecov
      - run:
          name: Upload Coverage to Codecov
          command: |
            if [ -n "$CODECOV_TOKEN" ]; then
              bash <(curl -s https://codecov.io/bash)
            else
              echo "Codecov token is not set. Skipping upload."
            fi

      # Analyse Checkstyle
      - run:
          name: Checkstyle Analysis
          command: mvn checkstyle:check

      # Ajouter les clés SSH
      - add_ssh_keys:
        # Vous pouvez également laisser CircleCI gérer la clé automatiquement si elle est correctement ajoutée dans votre projet
        # Les clés SSH associées à votre projet doivent être disponibles sans spécifier de fingerprint

      # Génération de la Javadoc
      - run:
          name: Generate Javadoc
          command: mvn javadoc:javadoc

      # Déploiement de la Javadoc sur GitHub Pages
      - run:
          name: Deploy Javadoc to GitHub Pages
          command: |
            mkdir -p target/github-pages
            cp -r target/site/apidocs/* target/github-pages/
            git config --global user.email "oumayma.bousaid@gmail.com"
            git config --global user.name "Oumayma-Bousaid"
            git clone git@github.com:${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}.git gh-pages
            cd gh-pages
            git checkout gh-pages || git checkout -b gh-pages
            cp -r ../target/site/apidocs/* ./
            git add .
            git commit -m "Update Javadoc"
            git push origin gh-pages --force

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
