# Utilisation de la version 2.1 du moteur de pipeline de CircleCI
# Voir : https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

# Définition des jobs pour le workflow
jobs:
  build:
    docker:
      - image: cimg/openjdk:8.0  # Utilisation de l'image Docker OpenJDK 8

    steps:
      - checkout  # Récupération du code source
      - run:
          name: Build
          command: mvn -B -DskipTests clean package  # Compilation sans exécuter les tests
      - run:
          name: Build with Maven
          command: mvn clean install  # Compilation complète avec Maven
      - run:
          name: Run Tests and Generate Coverage Report
          command: mvn test jacoco:report  # Exécution des tests et génération du rapport de couverture
      - run:
          name: Upload Coverage to Codecov
          command: bash <(curl -s https://codecov.io/bash)  # Envoi du rapport de couverture à Codecov

# Orchestration des jobs dans le workflow
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master  # Exécution du job 'build' uniquement sur la branche 'master'
